name: ci-golang-sonarcloud
on: 
  pull_request:
    branches:
      - develop


jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run:  go test -coverprofile=coverage.out
      


